Added IDbService interface, started an AWS implementation, etc.
User5842/rank-bot pull request #13
Opened 2022-03-17 18:55 UTC by johntdowney

Hope this isn't too bad :D.

2022-03-17 23:49 UTC, User5842 requested changes
Awesome start and most of my comments are nitpicks :) I hope this helps.

2022-03-17 23:49 UTC, User5842 commented on src/data-access/DbServiceAws.ts
> +
Nit: Remove this extra line.

2022-03-17 23:49 UTC, User5842 commented on src/interfaces/IAttributeDefinition.interface.ts
> +  AttributeName: string;
Nit: Add a new line after this.

2022-03-17 23:49 UTC, User5842 commented on src/interfaces/IDbService.interface.ts
> +     * @param keySchema The key schema for the table, consisting of a list of IKeySchemaElement objects
For consistency, can we add a period after this sentence. Also, on line 13.

2022-03-17 23:49 UTC, User5842 commented on src/data-access/DbServiceAws.ts
> +            ks.push({ AttributeName: k.AttributeName, KeyType: k.KeyType});
Perhaps I am reading this wrong but do we need to create `ks` here? Doesn't the `keySchema` parameter already contain this? The same goes for the `as` array below.

2022-03-17 23:49 UTC, User5842 commented on src/data-access/DbServiceAws.ts
> +            ks.push({ AttributeName: k.AttributeName, KeyType: k.KeyType});
At any rate, if it needs to be like this, consider using `map` for your array creation, e.g.:

```
const ks: AWS.DynamoDB.KeySchemaElement[] = keySchema.map((k) => ({
    ...k,
}));

const as: AWS.DynamoDB.AttributeDefinition[] = attributionDefinitions.map(
    (a) => ({ ...a })
);
```

2022-03-17 23:49 UTC, User5842 commented on src/data-access/DbServiceAws.ts
> +const dynamodb = new AWS.DynamoDB();
Can this throw? If so, what happens?

2022-03-17 23:49 UTC, User5842 commented on src/data-access/DbServiceAws.ts
> +        return new Promise<any>((resolve, reject) => {
TIL that the type parameter for a Promise denotes that of its `resolved` value. A `rejected` value is _always_ `any`. Therefore, we should be able to use the `AWS.DynamoDB.CreateTableOutput` type here. The same goes for the `any` in your `IDbService.interface.ts` file.

2022-03-18 01:32 UTC, johntdowney commented on README.md
> +###Installation
Didn't know this.

2022-03-18 01:33 UTC, johntdowney commented on src/data-access/DbServiceAws.ts
> +
"Nit"?

2022-03-18 18:28 UTC, johntdowney commented on src/data-access/DbServiceAws.ts
> +            ks.push({ AttributeName: k.AttributeName, KeyType: k.KeyType});
Nice! Good syntax. Yes I need to be more comfortable doing that.. especially that weird spread operator into an object part, `{ ...a }`.

2022-03-18 18:30 UTC, johntdowney commented on src/data-access/DbServiceAws.ts
> +            ks.push({ AttributeName: k.AttributeName, KeyType: k.KeyType});
Omg it's so much cleaner.

2022-03-18 18:33 UTC, johntdowney commented on src/data-access/DbServiceAws.ts
> +const dynamodb = new AWS.DynamoDB();
You know, I'm not sure, but I don't think so.  The logging is probably ill-placed.  I had originally intended to use it in an initialization routine, where the tables are created if they do not exist, etc.

I don't think this is currently asynchronous.  I think it's just updating the server configuration.  I think that if the configuration is wrong, it will throw errors in the individual asynchronous calls.

2022-03-18 18:34 UTC, johntdowney commented on src/data-access/DbServiceAws.ts
> +const dynamodb = new AWS.DynamoDB();
At least, if you mean "can this throw an exception?"

If you mean like... "can it throw down?"  I don't know, maybe, if you provoke it enough.

2022-03-18 18:38 UTC, johntdowney commented on src/data-access/DbServiceAws.ts
> +        return new Promise<any>((resolve, reject) => {
You're right, but what I don't like about this, is that it binds it to DynamoDB, which is kind what I'm avoiding by writing it this way.

I will just make another generic interface that corresponds to AWS's CreateTableOutput interface.

2022-03-18 21:20 UTC, User5842 approved these changes

2022-03-18 21:20 UTC, merged